### ISSUE TITLE
port phrases & negative sampling in word2vec

### ISSUE THREAD

**Issue by piskvorky** [piskvorky/gensim#130]
A few days ago Tomas Mikolov &al published a new article on word2vec:  http://arxiv.org/pdf/1310.4546.pdf

It deals with negative sampling and phrases, the results look good => let's port it from the C to gensim.

Solution outline
-----------------------

**Negative sampling**: add another parameter `negative` to the constructor + to `train_sentence`. Implement as a code branch both in the clean readable NumPy version (where it says `TODO: add negative sampling?` in `word2vec.py`) and inside `word2vec_inner.pyx` (optimized cython code). 

**Phrases**: I'm thinking of a transformation class = takes a "normal" sentence iterator as input and calculates the necessary frequencies etc., like in the C code: `phrases = Phrase(sentences, passes=1)`. Then when you iterate over `phrases` it yields out the same sentences, only with words merged into phrases. For example `for sentence in Phrase([['new', 'york', 'is', ...], ...]`) => `['new_york', 'is', ...] ...`. And of course, for training, instead of `Word2Vec(sentences)` you'd do `Word2Vec(Phrase(sentences))`.
The `passes` parameter controls the number of merging passes, so that we can form longer phrases than bigrams, too (`new_york_times` etc).

**Comment by tmylk** [comment]
Phrases implemented in https://github.com/piskvorky/gensim/pull/261

**Comment by hwsamuel** [comment]
I'm having the following problem with bigrams that might possibly related to what @sumitborar noted. First of all, my objective is to get a vector representation of phrases within a corpus. I can create bigrams and then call `model = word2vec.Word2Vec(bigrams[sentences],min_count=1)`. The problem is that the model is filtering out many bigrams that are important. For example, I see "this_report" in the bigrams list, but on inspecting the model via `model.vocab.keys()`, I don't see "this_report". The WordVec model seems to be filtering some bigrams that I don't want filtered. I've tried different values of `min_count`, including 0, but it doesn't seem to help.
