### ISSUE TITLE
loading a matrix using svmlight cause shape to shrink

### ISSUE THREAD

**Issue by xeechou** [piskvorky/gensim#276]
I had a issue when I using
  ` gensim.matutils.corpus2csc(corpora.SvmLightCorpus(file_that_I stored))`
I actually got a matrix shorter than I stored. BTW, the code that I used for storing is:
   ` corpora.SvmLightCorpus.serialize(file_to_store, matutils.Sparse2Corpus(the_matrix))`

Is there any way I can get rid of this problem? Please help

**Comment by piskvorky** [comment]
That format doesn't store the number of features, so the number of features must be guessed from the data automatically by gensim.

For example, if you have 10,000 features, but the highest feature ID appearing in your stored dataset is 9,667, then gensim will decide the number of features is 9,668.

You can fix this easily by giving the [num_terms parameter to corpus2csc](http://radimrehurek.com/gensim/matutils.html#gensim.matutils.corpus2csc).

Or if the problem is something else, give more description, I'm not sure what you mean by "shape shrinks".

**Comment by xeechou** [comment]
Thanks, that's what I meant. I had another question, when I generated ".mm" file, additional ".index" file was generated as well. I wonder if they are helpful, but they are binary and I can't find what they are about online.

Thanks again for helping me

**Comment by piskvorky** [comment]
That file allows you to do `corpus[5233]` (random indexing into the .mm corpus, rather than just linear streaming `for vec in corpus: ...`). It's not vital for anything though, you can safely delete it.
