### ISSUE TITLE
num_terms calculated by max value in id2word keys?

### ISSUE THREAD

**Issue by SeanWhipple** [piskvorky/gensim#317]
I create a corpus and create my own `id2word` dictionary.  However my IDs are created by a hash function (so they can take on large values).  In ldamodel.py there is the following block of code

```python
if self.id2word is None:
            logger.warning("no word id mapping provided; initializing from corpus, assuming identity")
            self.id2word = utils.dict_from_corpus(corpus)
            self.num_terms = len(self.id2word)
elif len(self.id2word) > 0:
            self.num_terms = 1 + max(self.id2word.keys())
else:
            self.num_terms = 0

if self.num_terms == 0:
            raise ValueError("cannot compute LDA over an empty collection (no terms)")
```

When the `id2word` is not specified it seems like `num_terms` is dictated by the number of elements in `id2word.keys()`.  However when it is specified it seems to assume that the max value in the dictionary indicates the number of elements.  This is causing my model to assume there are a TON of elements.  Is there a way to get around this?

**Comment by piskvorky** [comment]
Yes, the ids are expected to be a natural sequence of feature ids, to serve as indexes. If your ids are something else (a hash), you can simply remap them into indices. I think that's the simplest solution.

In other words, instead of `word (string) => id (integer index)`, you'd do `word (string) => hash (whatever) => id (integer index)`.

But I don't think there's a way around this sequential mapping -- in principle, LDA need to allocate some storage for each feature, as a large matrix. And these integer indexes from `id2word` are used to determine which matrix column represents which word. You can't just allocate a matrix for your entire hash space. The indices are a way to explicitly sparsify the feature space.

You can have a look at [gensim's HashDictionary](http://radimrehurek.com/gensim/corpora/hashdictionary.html), which implements something similar (the "hashing trick").

**Comment by SeanWhipple** [comment]
I created such an implementation already, I guess I just thought that at that point, you've hashed all you're going to do, the number of features is not going to be `max(dict.keys())` but the number of features can be represented by the `len(dict.keys())`.

I've worked around with your suggestion, thanks
