### ISSUE TITLE
Doc2Vec Tutorial and "min_count" Misleading, constraining

### ISSUE THREAD

**Issue by KCzar** [piskvorky/gensim#346]
Tutorial (http://radimrehurek.com/2014/12/doc2vec-tutorial/): 
"I suspect the most popular use case would be to have a single label per sentence which is the unique identifier for the sentence"

Word2Vec AND Doc2Vec (https://github.com/piskvorky/gensim/blob/develop/gensim/models/doc2vec.py) parameter definition:
`min_count` = ignore all words with total frequency lower than this.

The default for min_count in both Word2Vec and Doc2Vec is 5.

I think there's a lack of clarity about how to interpret min_count, particularly in Doc2Vec, where the default for min_count is 5.  

For starters, it's unclear from the definition whether min_count should apply to labels as well as words within sentences (though one might assume it applied to labels as well as words given that the code doesn't seem to implement any redefinition from Word2Vec - behavior which would seem to be undesirable).  

One would assume that if you have unique sentence labels, as the tutorial suggests is the most common use case, then min_count of 5 would eliminate all document labels as they would occur once per sentence.  What I'm finding however is that the unique sentence labels that get excluded are only labels for sentences with fewer than 5 words total.  That doesn't seem to line up well with the description that suggests "min_count" pertains to the frequency of the word/label, not the number of words in the corresponding sentence.

So I assume the only practical way to use Doc2Vec with unique sentence labels is with min_count = 1 (which the tutorial doesn't show).  This also prevents setting a min_count for sentence words that is greater than 1.  

Is this a problem we can easily solve (or am I missing something, and it's not really a problem)?

**Comment by gojomo** [comment]
This is a known problem with the current implementation's mix of words and document-labels in the same vocab structures – which also overloads the Vocab.count to mean 'words in sentences with this label' rather than 'occurrences of this label. 

It will soon be fixed by tracking words and doc-labels separately. (You can try this now in my dev branch – github.com/gojomo/gensim – but note there are still other gaps and untested/underdocumented parts there that will be equally frustrating as this issue.) 

You've already discovered one workaround – sticking with a min_count (such as '1') that's less than the length of any documents-of-interest. You could also patch doc2vec.py (around line 207) such that any lable-derived Vocab has an artificially-high count, above whatever min_count you really want to use.

**Comment by KCzar** [comment]
Sounds good - I suppose that gives me options.  I'll have a look at the dev branch.

Have you guys ever experimented with memory mapping the vectors for either Word2Vec or Doc2Vec?

**Comment by gojomo** [comment]
A memory-mapped numpy array *is* an option on the new helper object that holds the doc-vectors. (I suppose it could be offered or allowed on the vocabulary vectors, too. But, the more-random pattern of access there would likely cause a negative performance surprise, if someone tried to use that to train a vocabulary larger than their main memory.)

**Comment by gojomo** [comment]
The separation of docvecs that sidesteps these vocab-colliding/min_count issues (and allows docvecs-in-training to be memmap'd) is available for review/integration at PR #356 .

**Comment by gojomo** [comment]
Closing as resolved by 0.12.
