### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by msalameh83** [piskvorky/gensim#392]
Hi , 
I am still getting this error:
OverflowError: Python int too large to convert to C long
on line 112 of word2vec.py

I have tried solutions discussed earlier and changed the hash function, but it did not work.

Also, shouldn't line 119 be indented ?
Thanks

**Comment by gojomo** [comment]
Yes, line 119 is under-indented – good catch, I'll fix. 

I can force a similar error as you get on line 112 if I try `numpy.random.randint(2**64)`, so I suspect your error is because on 32-bit python, `2**32` can cause a problem for `numpy.random.randint()`. 

Can you confirm you're on a 32-bit python? (What does `python --version` and `python -c "import sys; print(sys.maxsize)"` say?) Is moving to a 64-bit python an option? 

This spot could (and probably should) be adapted to still work under 32-bit python. But, given the other spot you got the same error, and the possibility of other similar recurring problems elsewhere (because the developers and build/test machines are probably all 64-bit python), the approach likely to skip the most future problems would be to use a 64-bit python.

Also, if you're running these pure-python method implementations, your training will go at about 1/100th the speed compared to having the c-variants working. So getting that working might both sidestep this issue and offer other benefits.

**Comment by gojomo** [comment]
The change made in 726102d *may* get you past this error; could you please try it? (Though, still, the main goal should be to get the c-extension code working.)

**Comment by piskvorky** [comment]
@msalameh83 ping.

Can you please check the latest gensim fixed this? Did @gojomo 's answers (and questions) resolve the issue for you?

**Comment by msalameh83** [comment]
Sorry for late reply.
Yes it works now
Thanks

**Comment by piskvorky** [comment]
Great, thanks!
