### ISSUE TITLE
Batch sentences inside word2vec/doc2vec

### ISSUE THREAD

**Issue by piskvorky** [piskvorky/gensim#450]
...for an additional speed up (GIL acquired only once per batch, not once per sentence).

This is especially critical for very short documents, where the GIL overhead becomes deadly.

**Comment by gojomo** [comment]
Best policy is probably to send in the largest batch that fits within the MAX_SENTENCE_LENGTH of the cython code (in word2vec_inner.pyx/doc2vec_inner.pyx). The whole batch would be mapped into the C-structures (in still-GIL section), then one extra nested loop inside the NOGIL section would move through the ranges of prepped data. An initial estimate of the potential, by simply concatenating batches of 10 ~13-word sentences into ~130-word sentences, sped a run on 8-cores/8-workers by 2x.

**Comment by olavurmortensen** [comment]
Hi guys. I'm working on this issue on [a branch of my own fork of Gensim](https://github.com/olavurmortensen/gensim/tree/batch_sentences). I don't experience any speed up, and I don't know why. Any input would be greatly appreciated.

I've done it in the way discussed in this thread. Pretty much all the changes are in the train method, in _do_train_job, and in word2vec_inner.pyx. 

Note I am only working on the skip-gram method in word2vec as of yet.

**Comment by piskvorky** [comment]
@olavurmortensen can you open a pull request against `develop`? Easier to discuss changes that way.

**Comment by olavurmortensen** [comment]
[Done](https://github.com/piskvorky/gensim/pull/468).

**Comment by gojomo** [comment]
Thanks for diving into this! A pullreq would make things easier to review, but from a quick glance a few first thoughts:

* the python MAX_SENTENCE_LEN (really better thought of as MAX_WORDS_IN_BATCH) should match the cython MAX_SENTENCE_LEN, since the aim is to feed the optimized code the largest chunk of words it can handle
* if you're only sending in up-to-200 words at a time (your current MAX_SENTENCE_LEN), those are still pretty-small examples. (How few words were your examples, *before* trying batching?)
* in the cython code, the 2-D arrays (of the form `indexes[MAX_NUM_SENTENCES][MAX_SENTENCE_LEN]`, etc) are wasting a *lot* of stack-allocated memory: each is 100*10000=1 million 4-byte ints (4MB)... I suspect this isn't good for cache efficiency. I was thinking instead to pack as many batched examples as possible consecutively into a single-dimensional array (still like `indexes[MAX_SENTENCE_LEN]`, etc), with some other array(s), of length MAX_NUM_SENTENCES, pointing to each start/end range (so the contexts don't bleed together). 

Just curious, for the data on which you are seeking a speed-up, what is the usual length (in words) of your examples before batching, and what 'window' value are you using?

**Comment by olavurmortensen** [comment]
Hi guys. I require some assistance. I'm getting a "segmentation fault", which seems to happen as soon as I call the `train_batch_sg` function (in word2vec_inner.pyx). I didn't get this error before, I've made little changes to the Cython code since then, and can't figure out what's causing it.

Have any of you experienced this before? Do you have any idea what might cause it?

**Comment by gojomo** [comment]
Essentially reading/writing of memory at the wrong place (very easy in c/cython arrays) may cause a 'segmentation fault'. They can be hard to track down, because sometimes the buggy access is 'legal enough' that it doesn't immediately trigger a fault, but creates corruption that causes a later fault (on a more innocent-looking line). And similarly, because the raw heap memory allocations vary from run to run, sometimes they're triggered only intermittently, when the mistaken reads/writes land in the wrong neighboring data-structures. (Though, even when the segfault isn't triggered, silent corruption may be occurring.)

To see the exact line and stack/heap state at the fault, you'd need to run inside a system debugger (like gdb or lldb, as appropriate) – either on initial launch or by forcing a core image of the process to be dumped at the time of the error, then attaching the debugger to that. 

It may help to turn the 'bounds check' directive atop cython files back 'on', so that you get reported errors as close to the true error as possible. 

One of Radim's comments on the PR identified a place where data may have been passed in excess of the ability of the (fixed-size) cython arrays to handle it. (Specifically: https://github.com/piskvorky/gensim/pull/468#discussion-diff-40516456 ) That's exactly the sort of thing that would cause memory corruption and (eventually) a segfault. 

Does the PR branch have your latest, segfault-triggering code? Do you have a dataset/parameters that will reliably trigger the fault? (For example, does one of the `tests/test_word2vec.py` unit test suffice?)

**Comment by piskvorky** [comment]
Please continue discussion in the PR as indicated.

**Comment by tmylk** [comment]
Implemented in https://github.com/piskvorky/gensim/pull/535
