### ISSUE TITLE
seed doc2vec.infer_vector() with mean of word vectors to get more stable results

### ISSUE THREAD

**Issue by tro4els** [piskvorky/gensim#460]
The intuition behind this modification is that in the current version of gensim we are likely get a seed vector far from the desired optimum. Using the vectors for the words in the input sentence biases the result in (hopefully) the right direction. The modification can be implemented by substitution of
`doctag_vectors[0] = self.seeded_vector(' '.join(doc_words))`
by
`doctag_vectors[0] = np_sum([self.syn0[self.vocab[w].index] for w in doc_words],axis=0)/len(doc_words)`
in line 664 of doc2vec.py

**Comment by piskvorky** [comment]
Interesting idea! Let's hear the thoughts of @gojomo, our doc2vec mastermind.

**Comment by gojomo** [comment]
Interesting idea! 

Have you tried this on real data and observed a quantifiable improvement in some measure of the inferred-vector desirability? 

I believe inference ca even start with the zero vector, and with enough iterations would expect good results – we're only using the current seeding to maintain consistency to how the exact same document would have been handled, if it had been part of the original training batch. (I'd expect the main benefit of a "better starting point" to be equally-effective inference in fewer-steps, rather than a better end-result for someone patient enough to wait out a long inference.)

If this approach helps, it may work better as an option, for the user to pass in their own initial-value or seeding-policy, rather than a default.  

Why? One of the Doc2Vec training modes doesn't use word-vecs at all: DBOW without the `dbow_words=1` option. There, the word-vecs at the end of training are still just the random initialized values, so they'd not be of any use. (Ideally the code wouldn't even bother allocating/initializing `syn0` in that case, but that hasn't yet been optimized.)

In another mode, DM-with-a-concatenative-input-layer (`dm=1, dm_concat=1`), the doc-vecs supply a completely separate range of the input layer than the context-window word-vecs. Thus, the training forces no consistent relationship between them. (They wouldn't even need to be the same dimensionality, though the code doesn't yet support this.) 

It's the DBOW-with-word-cotraining mode, or the DM/sum and DM/average modes, where word- and doc- vectors are handled interchangeably by the training process, and so wind up drwn from a compatible 'space'.

**Comment by tro4els** [comment]
The model I have tried so far is actually (``dm=1, dm_concat=1``) because it was my impression that both words and documents were embedded in the same space.
@gojomo says that there is no such correspondence, but my experience is that the seeding method actually yields more stable results.
The only reason I can think of is that the inference procedure actually does not move the vector significantly away from the seed. Hence I will look into the influence of changing the learning rate when calling ``infer_vector()``

**Comment by gojomo** [comment]
If stability is the aim, then yes, I would recommend trying other alpha/iteration counts on`infer_vector()`. It would probably be ideal to have inference be subject to some sort of dynamic learning-rate or stopping-decision, based on whether the candidate vector is still improving at the training-goal. 

That's not yet implemented, but might not be too hard to beneficially add, especially in the relatively-constrained inference scenario.

If perfect reproducibility from inference-to-inference is a goal, also see the discussion at #447 – you should be able to force it by eliminating the usual sources of random-seeding or leftover random-state from earlier runs.

**Comment by tro4els** [comment]
Thanks. I am not interested in total reproducability though, just well estimated document vectors.
Yes, it might be a useful addition to be able to set some kind of convergence tolerance.

**Comment by tmylk** [comment]
@gojomo Should this go on the wishlist or be closed?

**Comment by gojomo** [comment]
No proven need, but perhaps other starting-vectors would be interesting to people, so I've mentioned it on the wishlist 'misc ways to improve' issue #515.
