### ISSUE TITLE
Doc2Vec gives PyObject_Malloc (out of memory) error, how to use disk space?

### ISSUE THREAD

**Issue by stejesh** [piskvorky/gensim#469]
I'm using the Doc2Vec to train a model from a 16MB text file
This is **part** of the code i'm using

```sh
model = Doc2Vec(min_count=1, window=10, size=100, sample=1e-4, negative=5, workers=1)
model.build_vocab(sentences)
for epoch in range(10):
    model.train(sentences)
```

This code `model.train` causes my machine to give `PyObject_Malloc` errors which are very likely caused because of less available RAM

Is there anyway i can leverage my disk-space to get this training done?

**Comment by gojomo** [comment]
16MB is tiny, so it's very unlikely anything Doc2Vec related is exhausting your RAM. What is the full error stack for the `PyObject_Malloc` error?

(Separately: your manual invocation of 10 training epochs, without any explicit management of `alpha` and `min_alpha`, means that each of your 10 epochs will go from the default starting-alpha of 0.025 to the default ending-alpha of 0.0001 – which is almost certainly not what you want. You should either let the class's `iter` parameter handle the corpus-repetition for you, so that the alpha descends smoothly from 0.025 to 0.0001 over the full 10 epochs, or explicitly manage the alpha/min_alpha yourself between calls to `train()`.)

**Comment by tmylk** [comment]
Closing as no report.
