### ISSUE TITLE
Mallet 2.0.8 read_doc_topics format changed

### ISSUE THREAD

**Issue by tmylk** [piskvorky/gensim#485]
Hi,

Seems like read_doctopics in gensim.models.wrappers.ldamallet needs to be changed.  Am I right?

In Mallet 2.0.7, doctopics.txt looks like:
#doc name topic proportion ...

0	0	158	0.1182170542635659	129	0.07170542635658915	111	0.04844961240310078 ...

So it makes sense to zip things in read_doctopics: zip(parts[::2], parts[1::2])

In Mallet 2.0.8RC2, doctopics.txt looks like:
0	0	2.8037970188132654E-5	1.9405424585156917E-5	2.8328585124176796E-5 ...

I am hoping topic probabilities follow the same order (topic1, topic2, ...) in all lines of this new doctopics.txt file.

Also This [line](https://github.com/piskvorky/gensim/blob/develop/gensim/models/wrappers/ldamallet.py#L51) needs to be changed additionally (no header in the new version).

From [mailing list](https://groups.google.com/d/msg/gensim/L4ME7M6kbP0/bmfg8QDHBwAJ)

**Comment by ziky90** [comment]
Is anyone working on this already?
Would you like to keep the compatibility with Mallet 2.0.8RC2 as well? For example using some automatic mallet version determining or version parameter?

**Comment by piskvorky** [comment]
@ziky90 yes, that sounds like the best option: detect dynamically what format it is (pre/post 2.0.8) and adjust parsing accordingly.

We definitely want to (have to) keep compatibility with the old Mallet too.

I don't know whether there have been any other changes in Mallet. If so, we may have to introduce a new explicit parameter into the wrapper (`mallet_version`), or detect the version explicitly somehow, rather than just adjust the format parsing. If it's just the parsing, probably no need to bother users with it, we can auto-detect.

**Comment by tmylk** [comment]
@jeiranj had ideas for the PR on [the mailing list](https://groups.google.com/d/msg/gensim/L4ME7M6kbP0/bmfg8QDHBwAJ)

**Comment by cscorley** [comment]
Closing, this issue should be fixed by @jeiranj!
