### ISSUE TITLE
Doc2Vec - Training abruptly ceases

### ISSUE THREAD

**Issue by newterminator** [piskvorky/gensim#493]
I am training the three main models on a concatenated (alldata-id.txt) file of size 893 MB. I followed the doc2vec notebook example, and got to the Stage 10 as in the example notebook to train for 20 passes. 

I ran it first on i7 Core - 4 Core, 32 GB Ram and it just seems not go any further beyond 16 passes...

Then I tried the same on MBP with i7 - 4 Core, 16 GB Ram and it goes on till 6 passes ... 

![doc2vec](https://cloud.githubusercontent.com/assets/5087437/10599543/11db34fa-76d1-11e5-9f68-07c27274046c.png)

In both instances I left the computers running for 2 days, but the output as shown above from the desktop, does not change after the first 4 hours in to the run.

Any ideas as to why this might be happening. On the desktop the free ram was still 14 Gb after two days. So couldn't be memory issues.

**Comment by gojomo** [comment]
Not sure what might cause this. I know OSX 'app nap' can sometimes mistakenly see long-running python compute processes as inactive and thus individually put them into battery-saving suspension. Some ways to disable it are discussed in the thread at: https://groups.google.com/a/continuum.io/forum/#!msg/anaconda/kvWVtW40aDI/cr9IkGdyzY4J

If that doesn't help, other things I'd check...

* is the process still shown as active at all in Process Monitor / top, after output stops updating?
* can the cell be interrupted from the IPy notebook controls? 
* have you turned on logging (as for example by the cell at the bottom of the example notebook) in case that shows something else?

Occasionally the OSX Process Monitor doesn't seem to show all the uses of memory – for example, none of the columns I've found seem to reflect the full memory footprint of VMWare guest OSes. But I wouldn't generally expect it to be a memory issue mid-training, because the Word2Vec/Doc2Vec models allocate the bulk of their objects up front (when the word-scan is done), then don't grow any more.

**Comment by newterminator** [comment]
Thanks Gordon, for writing a detailed and quick response. I first of all spent time going back to Mavericks from Yosemite which was causing freezing problems for me since updating from Mavericks(10.9.5). 

I visited the direct link you mentioned and applied the command as mentioned in the thread. I am going to rerun the notebook again tonight and see if it goes through all the 20 passes this time. 

If that doesn't work then I will check the other points as you mentioned.

**Comment by gojomo** [comment]
@newterminator - does it seem the App Nap was the main culprit? (If so, I'll add more detail to the issue title to make it easier to find in the future...)

**Comment by newterminator** [comment]
@gojomo Yes you were right on 100% about the app nap being the culprit. Thank you once again!!!
