### ISSUE TITLE
Can't save & load after using load_word2vec_format

### ISSUE THREAD

**Issue by simonzack** [piskvorky/gensim#525]
When saving a `load_word2vec_format` model then loading it the following shows up:

    AttributeError: 'Vocab' object has no attribute 'sample_probability'

It's due to this check:

    for v in model.vocab.values():
        if hasattr(v, 'sample_int'):
            break  # already 0.12.0+ style int probabilities
        else:
            v.sample_int = int(round(v.sample_probability * 2**32))
            del v.sample_probability

But niether `sample_int` nor `sample_probability` are present.

**Comment by gojomo** [comment]
The gensim native `load()` method currently assumes the model was also originated/initialized as a native gensim model, with more internal state. The word2vec_format files only have vectors. There's intent to fix that or make the limitations clearer (see #499). 

Since such a model from `load_word2vec_format()` only has the vectors, you could just re-load from the original file (or re-save with `save_word2vec_format()`) – unless you're doing something non-standard to further modify the model after load.

**Comment by simonzack** [comment]
Thanks for the info I'll close for now.
