### ISSUE TITLE
Memory Error (Revisited)- Word2Vec

### ISSUE THREAD

**Issue by shirish93** [piskvorky/gensim#592]
Hi, I commented on issue 293 but wanted to raise a new issue, since I've verified it's not a hardware issue on my side.
https://github.com/piskvorky/gensim/issues/293#issuecomment-175026483

To quote myself:

>Hello, I seem to have encountered a similar issue. I'm using gensim with WinPython in one of my virtual machines with 16G memory. A model I have loads fine and works perfectly on a different system with 8GB memory in similar conditions, but when I run it in the VM, I get this:

>>word2vec.py", line 1266, in init_sims self.syn0norm = (self.syn0 / sqrt((self.syn0 ** 2).sum(-1))[..., newaxis]).astype(REAL) MemoryError 

>when trying to use the 'most_similar' functions for Word2Vec. I can load the model fine, and can retrieve the word vectors of words fine, but it seems to explode just when I try to access similarity-related functions (including 'doesn't match') etc. The closest existing issue I was with this. Any ideas?

Two observations: the memory usage does not seem to increase with the 'similarity' calls, and there's quite a bit of spare memory left. Additionally, when I turn the word: wordVector pairing into a dictionary, and *sort* the words by the cosine distances of their vectors to the input word/vector, I get a reasonably acceptable answer, while _still_ not running out of memory.

> I'm using scipy.spatial.distance.cosine to calculate the distances between word vectors.

I've not looked at the code for similarity search, but since it runs 'really' fast, I'm assuming it trades memory for speed? That _still_ doesn't explain the lack of change in memory footprint though.

Update: The offending code lies in line 1318 of current master.

Have opened the same data source in several other machines successfully.

My specs:
platform.machine: AMD64
platform.platform: Windows-7-6.1.7601-SP1
python version: 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] \(The WinPython distribution)
gensim version: very latest.

**Comment by gojomo** [comment]
Can you verify the exact python version in use on the "other machines" (that succeed on the same operation)? Also, check the value of `model.syn0.nbytes` for your model? 

The info you've provided is still consistent with the theory (that was true for the earlier commenter on #293) that the MemoryError happens specifically because of limitations in 32bit Windows Python. The creation of the separate `syn0norm` array (unit-vector versions of all word vectors) needs another array of the same size as `syn0` – and thus another contiguous allocation of a large number of bytes. If, as is typical with large word2vec models, the `syn0` is already hundreds-of-MB (or even a GB or more), it's quite likely that in the 32bit address space (<4GB) that a 32bit executable is limited to using, there's just no contiguous memory space left for this operation.  

Best would be to move to a 64bit executable (though I know there may be special steps required to  get 64bit numpy/scipy working with 64bit Windows Python). 

If you need to work within 32bit address space, you can call `init_sims()` yourself (before it's needed by `most_similar()`), with the `replace=True` parameter. That destructively changes the `syn0` into the unit-vec values to save memory – see the comment for `init_sims()` at https://github.com/piskvorky/gensim/blob/ef9a9d97fa6681b6ff5cce57e011ba7ba5872847/gensim/models/word2vec.py#L1358 . Similarly, you could null-out the model's `syn1` or `syn1neg` (whichever is in use) to free up more memory – they're only needed during training, not `most_similar()` testing.

**Comment by shirish93** [comment]
The suggestion worked! Installed the 64-bit version, and everything appears to be functioning as desired.

If it is not already documented somewhere to _strongly_  suggest users to use the 64-bit versions, perhaps it should be done somewhere? Closing the issue, since it's fixed.

Thanks everyone !
