### ISSUE TITLE
word2vec.load has got an unexpected keyword argument 'hashfxn'?

### ISSUE THREAD

**Issue by liyi193328** [piskvorky/gensim#616]
when  training word2vec, I use hash function below:
<code>
def myhashfxn(obj):
    return hash(obj) % (2 ** 32)
</code>
then when I want to load word2vec, use myhashfxn, but get : 
**TypeError: load() got an unexpected keyword argument 'hashfxn'**
word2vec = gensim.models.Word2Vec.load("./word2vec",hashfxn=myhashfxn)
when I go to source code, the error line is:
**model = super(Word2Vec, cls).load(*args, **kwargs)**
but the class Word2Vec has the hashfxn option:
<code>
def __init__(
            self, sentences=None, size=100, alpha=0.025, window=5, min_count=5,
            max_vocab_size=None, sample=0, seed=1, workers=1, min_alpha=0.0001,
            sg=1, hs=1, negative=0, cbow_mean=0, hashfxn=hash, iter=1, null_word=0,
            trim_rule=None, sorted_vocab=1)
</code>

so where is the point? what should I do when load model use self defined hash function?

**Comment by gojomo** [comment]
The `load()` method doesn't take a `hashfxn` argument, hence the error. 

Nor is it the case that a `load()` function in general would take the same arguments as the `__init__()`.

Are you sure you need to use a non-default hash function? (What happens if you simply don't?)

If you must, are you sure that it wasn't saved with the model already, and reloaded even if not supplied as an extra argument? (If `myhashfxn()` is defined at the [top level of a module](https://docs.python.org/2/library/pickle.html#what-can-be-pickled-and-unpickled), it should be saved and reloaded via python pickling just fine.)

Finally, if you really need it and it can't be saved/reloaded normally, you could manually set it after `load()` similar to how it's initially set when the model is first created: https://github.com/piskvorky/gensim/blob/35e41f8594f75e269c855a9b276c7dfc502ef61d/gensim/models/word2vec.py#L433

**Comment by liyi193328** [comment]
@gojomo Thanks. I solved it by using runpy to make myhashfxn top level at last.
