### ISSUE TITLE
word2vec model has `sg=1` as the default parameter

### ISSUE THREAD

**Issue by sivasuryas** [piskvorky/gensim#643]
In the tutorial it has been mentioned that,
> sg defines the training algorithm. By default (sg=0), CBOW is used. Otherwise (sg=1), skip-gram is employed.

When I initialised a word2vec model with the config `gensim.models.Word2Vec(min_count=5, window=10, size=400, iter=3, workers=40)`
During the training phase, I could see the following log, as I have enabled logging.
> INFO:gensim.models.word2vec:training model with 40 workers on 567035 vocabulary and 400 features, using sg=1 hs=1 sample=0 and negative=0

Does it mean that, the default model is skip-gram and for CBOW I need to set `sg=0`

**Comment by gojomo** [comment]
Yes, you're reading that output right. The latest gensim release, 0.12.4, has a default of `sg=0` (CBOW) to match the default of the last version of word2vec.c from the original researchers. The documentation-comment matches. See:

https://github.com/piskvorky/gensim/blob/2b537271ce61aa29b0f4bfe107c1563e19fc23eb/gensim/models/word2vec.py#L346
https://github.com/piskvorky/gensim/blob/2b537271ce61aa29b0f4bfe107c1563e19fc23eb/gensim/models/word2vec.py#L360

You may be using an older release with a different default. In any case, you can always supply your own preferred value. 

Please use the forum https://groups.google.com/forum/#!forum/gensim for questions, rather than the bug/feature issue-tracker.
