### ISSUE TITLE
Converting from C word2vec to gensim model

### ISSUE THREAD

**Issue by nick-magnini** [piskvorky/gensim#672]
Hi,

I'm using this code to convert the original C word2vec model to the gensim one for fast loading. 
`model = Word2Vec.load_word2vec_format(word2vec_model,unicode_errors='ignore')
model.init_sims(replace=True) 
model.save(gensim_model)`

My original model is more than 30 GB and after converting to gensim model it's now less than 1 GB. Am I doing something wrong or this is a normal behaviour? Should I expect the same results from both models or size compressions come with sacrificing in performance?

**Comment by gojomo** [comment]
I wouldn't normally expect that much of a difference – but I haven't worked much with word2vec.c files. 

Straining to think of possible explanations, perhaps if many words were very long and compressable, or if many words were corrupt unicode that became smaller due to the `unicode_errors='ignore'` setting. Or maybe something strange has happened during training that made the vectors far more sparse/compressible than usual. 

Is there any suspicious logging output during any of the load_word2vec_format, init_sims, save steps? 

Does the model report the same number of vocabulary words after `load_word2vec_format()` as was reported as having been trained initially by word2vec.c? And then again after the `save()` and a subsequent `load()`? 

Do checks of `similar()` words still return expected neighbors, matching the output of the `distance.c` program of the word2vec.c project?

What sized file do you get if you `save_word2vec_format()`?

**Comment by nick-magnini** [comment]
I just checked. I can't load the saved model. I used `model = Word2Vec.load(gensim_model,mmap='r')` and it returns this error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gensim/models/word2vec.py", line 1465, in load
    v.sample_int = int(round(v.sample_probability * 2**32))
AttributeError: 'Vocab' object has no attribute 'sample_probability'`
I tried to other models, from loading load_word2vec_format to model.save and it returns the same when I load.

**Comment by gojomo** [comment]
Are you using the most recent gensim? A similar issue was fixed in #499.

**Comment by nick-magnini** [comment]
I used the latest and I was able to do the read the c word2vec and also I was able to save it and load it. However when I want to reload it with mmap I get this:
`model=Word2Vec.load(gensim_model,mmap='1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gensim/models/word2vec.py", line 1503, in load
    model = super(Word2Vec, cls).load(*args, **kwargs)
  File "gensim/utils.py", line 249, in load
    obj._load_specials(fname, mmap, compress, subname)
  File "gensim/utils.py", line 280, in _load_specials
    val = numpy.load(subname(fname, attrib), mmap_mode=mmap)
  File "/homes/myhome/.local/lib/python2.6/site-packages/numpy/lib/npyio.py", line 403, in load
    return format.open_memmap(file, mode=mmap_mode)
  File "/homes/myhome/.local/lib/python2.6/site-packages/numpy/lib/format.py", line 784, in open_memmap
    mode=mode, offset=offset)
  File "/homes/myhome/.local/lib/python2.6/site-packages/numpy/core/memmap.py", line 211, in __new__
    (valid_filemodes + list(mode_equivalents.keys())))
ValueError: mode must be one of ['r', 'c', 'r+', 'w+', 'readwrite', 'write', 'readonly', 'copyonwrite']`

I can load it without mmap. I yet to compare the similarities using the original model and the converted gensim one.

**Comment by gojomo** [comment]
(FYI I re-quoted your error with triple-backticks to preserve line-breaks.)

Why are you using `'1'` as the argument to `mmap`, where you were previously using `'r'`?

**Comment by nick-magnini** [comment]
I fixed it. Thanks. It's working now. The new version fixed the problem.

**Comment by nick-magnini** [comment]
After I load a huge model and try model.most_similar() then I get this as error:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "gensim/models/word2vec.py", line 1188, in most_similar
    self.init_sims()
  File "gensim/models/word2vec.py", line 1392, in init_sims
    self.syn0norm = (self.syn0 / sqrt((self.syn0 ** 2).sum(-1))[..., newaxis]).astype(REAL)
MemoryError

**Comment by piskvorky** [comment]
That line looks very memory-inefficient (temporary vars)... we should replace it by `numpy.empty()` + an explicit loop to initialize `syn0norm` row-by-row.

**Comment by gojomo** [comment]
@nick-magnini - if you'll only be using the loaded model for `most_similar()`-type operations, you could explicitly call `init_sims(replace=True)` after loading, to do an in-place unit-normalization of the `syn0` vectors-array. (That'd avoid the surge in memory use from creating a separate `syn0norm`.)

@piskvorky, @tmylk – we can probably just reuse the loop above – the toggle on `replace` could affect what's in `syn0norm` (either `syn0` itself or a copy), then the unit-norming always happens in-place.

**Comment by piskvorky** [comment]
Oh yes, that's right. The code is pretty much already there, right above, I didn't realize.

**Comment by nick-magnini** [comment]
So you suggest to do it this way:

`model=Word2Vec.load(gensim_model)`
`model.init_sims(replace=True)`
`similars=model.most_similar(text)`

**Comment by nick-magnini** [comment]
Is this equal to `model=Word2Vec.load(gensim_model,mmap='r')` in practice?

**Comment by gojomo** [comment]
@nick-magnini – yes, with an explicit `init_sims(replace=True)` call, so that a single in-place normalization occurs before doing any similarity-lookups. No, adding an `mmap` parameter to the `load()`  wouldn't cause any in-place normalization to occur. (In fact, `mmap='r'` would likely prevent the later `init_sims(replace=True)` from working, because it will have created a read-only array that can't be normalized in-place.)

**Comment by nick-magnini** [comment]
So for faster most_similar its better to `init_sims(replace=True)`?

**Comment by gojomo** [comment]
No faster - it just uses less memory, perhaps avoiding the MemoryError you encountered, by doing the conversion of raw vectors to unit-normalized vectors in-place. (If you don't do `init_sims()` yourself, it'll be done for you the first similarity-lookup you do and be cached thereafter – so you pay the time-cost either way.)

**Comment by nick-magnini** [comment]
Thanks for the explanations.
